# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99fc2f305c701d8cb4b69d38a686c26205628977c301b5215290bb1962b460868739611cd525e34d22955728803b8f6174c9eff80fef0644f7f7bb68c9e6c3f8

test:
  secret_key_base: 7d64834ae6b5bbda55254dfb74b6a2b6255efecc5174026828d40e28c919380dbf0f0988222fc87245c2e3e6464b237c25b433236eca4bd2d3108a318524c7cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
